[package]
name = "aquatic_ws"
version = "0.1.0"
authors = ["Joakim Frostegård <joakim.frostegard@gmail.com>"]
edition = "2018"
license = "Apache-2.0"

[lib]
name = "aquatic_ws"
path = "src/lib/lib.rs"

[[bin]]
name = "aquatic_ws"
path = "src/bin/main.rs"

[dependencies]
bittorrent_udp = { path = "../bittorrent_udp" }
cli_helpers = { path = "../cli_helpers" }
flume = "0.7"
hashbrown = "0.7"
histogram = "0.6"
indexmap = "1"
mimalloc = { version = "0.1", default-features = false }
mio = { version = "0.7", features = ["tcp", "os-poll", "os-util"] }
net2 = "0.2"
parking_lot = "0.10"
privdrop = "0.3"
rand = { version = "0.7", features = ["small_rng"] }
serde = { version = "1", features = ["derive"] }
slab = "0.4"
tungstenite = "0.10"

[dev-dependencies]
quickcheck = "0.9"
quickcheck_macros = "0.9"