[package]
name = "aquatic_ws"
version = "0.1.0"
authors = ["Joakim Frostegård <joakim.frostegard@gmail.com>"]
edition = "2018"
license = "Apache-2.0"
description = "Blazingly fast, multi-threaded WebTorrent tracker"
repository = "https://github.com/greatest-ape/aquatic"

[lib]
name = "aquatic_ws"
path = "src/lib/lib.rs"

[[bin]]
name = "aquatic_ws"
path = "src/bin/main.rs"

[dependencies]
anyhow = "1"
async-tungstenite = "0.15"
aquatic_cli_helpers = "0.1.0"
aquatic_common = "0.1.0"
aquatic_ws_protocol = "0.1.0"
core_affinity = "0.5"
either = "1"
futures-lite = "1"
futures = "0.3"
futures-rustls = "0.22"
glommio = { git = "https://github.com/DataDog/glommio.git", rev = "4e6b14772da2f4325271fbcf12d24cf91ed466e5" }
hashbrown = { version = "0.11.2", features = ["serde"] }
histogram = "0.6"
indexmap = "1"
log = "0.4"
mimalloc = { version = "0.1", default-features = false }
privdrop = "0.5"
rand = { version = "0.8", features = ["small_rng"] }
rustls-pemfile = "0.2"
serde = { version = "1", features = ["derive"] }
slab = "0.4"
tungstenite = "0.15"

[dev-dependencies]
quickcheck = "1.0"
quickcheck_macros = "1.0"
