[workspace]

members = [ 
    "aquatic",
    "aquatic_cli_helpers",
    "aquatic_common",
    "aquatic_http",
    "aquatic_http_load_test",
    "aquatic_http_protocol",
    "aquatic_udp",
    "aquatic_udp_bench",
    "aquatic_udp_load_test",
    "aquatic_udp_protocol",
    "aquatic_ws",
    "aquatic_ws_load_test",
    "aquatic_ws_protocol",
    "plot_pareto"
]

[profile.release]
debug = true
lto = true

[profile.bench]
debug = true
opt-level = 3
lto = true