[workspace]

members = [ 
    "aquatic",
    "aquatic_cli_helpers",
    "aquatic_common",
    "aquatic_http",
    "aquatic_http_load_test",
    "aquatic_http_protocol",
    "aquatic_toml_config",
    "aquatic_toml_config_derive",
    "aquatic_udp",
    "aquatic_udp_bench",
    "aquatic_udp_load_test",
    "aquatic_udp_protocol",
    "aquatic_ws",
    "aquatic_ws_load_test",
    "aquatic_ws_protocol",
]

[patch.crates-io]
aquatic = { path = "aquatic" }
aquatic_cli_helpers = { path = "aquatic_cli_helpers" }
aquatic_common = { path = "aquatic_common" }
aquatic_http_load_test = { path = "aquatic_http_load_test" }
aquatic_http = { path = "aquatic_http" }
aquatic_http_protocol = { path = "aquatic_http_protocol" }
aquatic_toml_config_derive = { path = "aquatic_toml_config_derive" }
aquatic_toml_config = { path = "aquatic_toml_config" }
aquatic_udp_bench = { path = "aquatic_udp_bench" }
aquatic_udp_load_test = { path = "aquatic_udp_load_test" }
aquatic_udp = { path = "aquatic_udp" }
aquatic_udp_protocol = { path = "aquatic_udp_protocol" }
aquatic_ws_load_test = { path = "aquatic_ws_load_test" }
aquatic_ws = { path = "aquatic_ws" }
aquatic_ws_protocol = { path = "aquatic_ws_protocol" }

[profile.release]
debug = true
lto = true

[profile.test]
opt-level = 3

[profile.bench]
debug = true
opt-level = 3
lto = true