[package]
name = "aquatic"
version = "0.1.0"
authors = ["Joakim Frostegård <joakim.frostegard@gmail.com>"]
edition = "2018"

[lib]
name = "aquatic"
path = "src/lib/lib.rs"

[[bin]]
name = "aquatic"

[[bin]]
name = "bench_handlers"

[[bin]]
name = "plot_pareto"

[dependencies]
bittorrent_udp = { path = "../bittorrent_udp" }
dashmap = "3"
indexmap = "1"
net2 = "0.2"
rand_distr = "0.2"
plotly = "0.4"

[dependencies.mio]
version = "0.7"
features = ["udp", "os-poll", "os-util"]

[dependencies.rand]
version = "0.7"
features = ["small_rng"]

[dev-dependencies]
quickcheck = "0.9"
quickcheck_macros = "0.9"