[package]
name = "aquatic_ws_load_test"
version = "0.1.0"
authors = ["Joakim Frostegård <joakim.frostegard@gmail.com>"]
edition = "2018"
license = "Apache-2.0"
repository = "https://github.com/greatest-ape/aquatic"

[[bin]]
name = "aquatic_ws_load_test"

[dependencies]
anyhow = "1"
aquatic_cli_helpers = "0.1.0"
aquatic_ws_protocol = "0.1.0"
hashbrown = { version = "0.9", features = ["serde"] }
mimalloc = { version = "0.1", default-features = false }
mio = { version = "0.7", features = ["udp", "os-poll", "os-util"] }
rand = { version = "0.8", features = ["small_rng"] }
rand_distr = "0.4"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
slab = "0.4"
tungstenite = "0.12"

[dev-dependencies]
quickcheck = "1.0"
quickcheck_macros = "1.0"
