name: 'cargo: build and test'

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose --workspace --all-targets
    - name: Run tests
      run: cargo test --verbose --workspace --all-targets
