name: 'cargo: build and test'

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-test-linux:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    container:
      image: rust:1-bullseye
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: sudo apt-get update -y && sudo apt-get install cmake libhwloc-dev -y
    - name: Build
      run: |
        cargo build --verbose -p aquatic_udp --features "cpu-pinning"
        cargo build --verbose -p aquatic_http
        cargo build --verbose -p aquatic_ws
    - name: Run tests
      run: cargo test --verbose --workspace --all-targets


  build-macos:
    runs-on: macos-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose -p aquatic_udp
