name: "Test HTTP and UDP file transfer"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test-transfer-http:
    runs-on: ubuntu-latest
    name: "Test BitTorrent file transfer over HTTP (with and without TLS) and UDP"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test file transfers
        uses: ./.github/actions/test-transfer-http-udp
        id: test_transfer_udp_http