name: "Test UDP, TLS and WSS file transfer"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test-transfer-http:
    runs-on: ubuntu-latest
    name: "Test BitTorrent file transfer over UDP, TLS and WSS"
    timeout-minutes: 20
    container:
      image: rust:1-bullseye
      options: --ulimit memlock=524288:524288
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test file transfers
        uses: ./.github/actions/test-transfer
        id: test_transfer
