name: "Test UDP and HTTP file transfer"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test-transfer-http:
    runs-on: ubuntu-latest
    name: Test BitTorrent file transfer over UDP and HTTP
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test file transfers
        uses: ./.github/actions/test-transfer-udp-http/action@v1
        id: test_transfer_udp_http